### PR TITLE
fix: deprecated ui.window

### LINKED ISSUE #127: No named parameter with the name 'window'. Error
AppData/Local/Pub/Cache/hosted/pub.dev/screenshot-1.3.0/lib/screenshot.dart:160:7: Error: No named parameter with the name 'window'.
      window: ui.window,
      ^^^^^^

### PR DESCRIPTION
**Pull request by Mayb3Nots**
Same as #132

Fixes #127

Flutter is adding support for multiple views [see](https://docs.flutter.dev/release/breaking-changes/window-singleton). This package have reference to deprecating code in the future.

### CODE REVIEW

**Comment by ritheshSalyan** [comment]
Thank you for contributing.

**Comment by AmirhosseinShk** [comment]
when be this version published on pub dev?

**Comment by Johnnyfdev** [comment]
> when be this version published on pub dev?

**Comment by EnduringBeta** [comment]
@ritheshSalyan I deeply appreciate your maintenance of this repo and responsiveness to get in this fix. Currently without an update pushed to pub.dev, I can't build my project unless I downgrade Flutter, which I don't want to do.

Are you able to publish the update?

**Comment by chillbrodev** [comment]
The use of PlatformDispatcher to access the view results in a corrupted image and the following error. The documentation states that we should use `View.of(context)`. Yes it states use of PlatformDispatcher, but it seems more complicated than using `.first` on `PlatformDispatcher.views`. We should make the breaking change to require use of Context. That is how I presented the fix over on #134 

This error occurred when I removed `context` from `captureFromWidget`. When the caller includes `context` everything works as expected.

Specifically the exception occurs at:
```
#324    RenderObjectToWidgetAdapter.attachToRenderTree
binding.dart:1155
#325    ScreenshotController.widgetToUiImage
```

```
ERROR - No MediaQuery widget ancestor found.
               ScaffoldMessenger widgets require a MediaQuery widget ancestor.
               The specific widget that could not find a MediaQuery ancestor was:
                 ScaffoldMessenger
               The ownership chain for the affected widget is: "ScaffoldMessenger ← Builder ← DefaultTextStyle ← CustomPaint ← Banner ← CheckedModeBanner ← Title ← Directionality ← _LocalizationsScope-[GlobalKey#9411a] ← Semantics ← ⋯"
               No MediaQuery ancestor could be found starting from the context that was passed to MediaQuery.of(). This can happen because the context used is not a descendant of a View widget, which introduces a MediaQuery
 ```

**Comment by Mayb3Nots** [comment]
> The use of PlatformDispatcher to access the view results in a corrupted image and the following error. The documentation states that we should use `View.of(context)`. Yes it states use of PlatformDispatcher, but it seems more complicated than using `.first` on `PlatformDispatcher.views`. We should make the breaking change to require use of Context. That is how I presented the fix over on #134
> 
> This error occurred when I removed `context` from `captureFromWidget`. When the caller includes `context` everything works as expected.
> 
> Specifically the exception occurs at:
> 
> ```
> #324    RenderObjectToWidgetAdapter.attachToRenderTree
> binding.dart:1155
> #325    ScreenshotController.widgetToUiImage
> ```
> 
> ```
> ERROR - No MediaQuery widget ancestor found.
>                ScaffoldMessenger widgets require a MediaQuery widget ancestor.
>                The specific widget that could not find a MediaQuery ancestor was:
>                  ScaffoldMessenger
>                The ownership chain for the affected widget is: "ScaffoldMessenger ← Builder ← DefaultTextStyle ← CustomPaint ← Banner ← CheckedModeBanner ← Title ← Directionality ← _LocalizationsScope-[GlobalKey#9411a] ← Semantics ← ⋯"
>                No MediaQuery ancestor could be found starting from the context that was passed to MediaQuery.of(). This can happen because the context used is not a descendant of a View widget, which introduces a MediaQuery
> ```

Hi @chillbrodev I did initially thought of making the `context` parameter required but that would mean breaking change and it would mean for certain cases where the context is not available it would not be possible to capture the widget. I would ultimately let the owner of this package decide which API would be best for the package. But from your error it seems like the widget you want to capture just needs a `MaterialApp` have you tried that?

**Comment by chillbrodev** [comment]
@Mayb3Nots Hey there, I guess I don't see a situation where you would want to capture a widget where context is not available.

We could also create a new function that requires context and leave the existing function as is where context is optional. That way it isn't a breaking change but follows the flutter design better.

In terms of MaterialApp, we had extra usage of the widget. When I removed the MaterialApp and didn't use context and it worked out. 

Tho my point is still valid that we should require context as PlatformDispatcher.views.first may not function correctly with foldables or external screens.

**Pull request merged**
